### ISSUE TITLE
Delete Old Servers and Nodes..

### ISSUE THREAD

**Issue by ne0ark** [sibblegp/Storj-Dashboard-Client#5]
It seems there is no option to delete old servers and nodes which are no longer active.

**Comment by sibblegp** [comment]
This is a bit of a difficult one.  Nodes that have not contacted StorJDash are automatically removed from the dashboard after a day.  Servers meanwhile, sometimes take some time to connect.  Should they automatically be removed after a day?  A week?  What if the server is just offline?

Would you prefer the ability to manually hide servers?

What would everyone prefer?

Thanks!

**Comment by Jurisg** [comment]
Can do 7 days remove same as contracts, user anyway can add node back later

**Comment by sibblegp** [comment]
I think since people won't know that they will be automatically removed, just having a button to remove (actually hide in the database sense) would be easier.  I'd just worry about people accidentally removing the wrong servers.  Although I could add a comment that says we will automatically remove servers after 7 days of inactivity.

**Comment by Jurisg** [comment]
Yes if here is place for warning add it To not get Questions about why my node is deleted.

**Comment by kocotech** [comment]
for both a server and a node i would like to see an option to delete it (by the user). The auto remove is i think not that intrestenting. A storj Farmer needs to have control over what he wants to show. For example i have one server that literally blew up last week and now im watching nodes that dont work anymore. I know they wont come online anymore, I know what server it is. if there was an option i could've deleted it the same day.

**Comment by Jurisg** [comment]
Manual option to remove is need too. But then need add field where user need additionally click checkbox or type " Yes"  to not delete by accident.

**Comment by sibblegp** [comment]
@kocotech That's an interesting point.  The nodes will still report because the config files still exist so it looks like they are active even though they are not.  So hiding manually is important.

Sounds like hiding manually makes the most sense for both and keeping the hiding nodes that haven't reported in 24 hours works as well.

This is a little more difficult to implement than it seems since I have to change every SQL query to ignore "deactivated" servers and nodes (which is about ~100 queries).  Right now I'm focused on the Windows installer.  Implementing auto-hiding of servers after 7 days would be very straightforward and something that can be done in an hour.

**Comment by felixbrucker** [comment]
I'll throw in another idea: send a mail after 7 days of inactivity with a link to confirm it is still "active".
If the link didn't get clicked within another 7 days the node in question will be removed.

**Comment by sibblegp** [comment]
After many requests (in this thread and off), I have taken the time to add a little (X) button to servers listed on the home page allowing you to hide them.  Nodes are automatically hidden after 24 hours of inactivity.  I may add automatic hiding of servers in the future, but since their storage may still count towards your overall monthly total, I don't think I want to hide them unless explicitly requested.

Enjoy!
